name: Build and Deploy

on:
  push:
    branches:
      - main # Trigger workflow on push to main branch

jobs:
  build:
    runs-on: ubuntu-latest # The type of machine to run the job on

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 # Checks-out your repository under $GITHUB_WORKSPACE

      - name: Setup OCaml
        uses: avsm/setup-ocaml@v2 # Sets up an OCaml environment
        with:
          ocaml-compiler: 5.1.0

      - name: Build project
        run: |
          sudo apt-get install -y libev-dev libgmp-dev pkg-config
          opam install . --deps-only
          opam exec -- dune build --release

      - name: Deploy to server
        run: |
          echo "${{ secrets.DEPLOY_SSH_KEY }}" > private_key
          chmod 600 private_key
          scp -i private_key ./_build/default/bin/main.exe laurentiu@161.97.155.104:/home/laurentiu/ocaml_chat/bin/main.exe
          scp -i private_key -r ./static  laurentiu@161.97.155.104:/home/laurentiu/ocaml_chat
